<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CourseOnline.Domain\CourseOnline.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Registrations\DTOs\Inputs\" />
    <Folder Include="Reports\Services\" />
    <Folder Include="StudentCourses\DTOs\Outputs\" />
    <Folder Include="Teachers\DTOs\Outputs\" />
  </ItemGroup>

</Project>
